CREATE_DATASOURCE = """
INSERT INTO RAG_SERVICE_DATASOURCE_CONFIG
(
    NAME,
    SOURCE_TYPE,
    CREATED_BY,
    CREATED_AT,
    UPDATED_AT
)
VALUES
(
    :name,
    'OCI_BUCKET',
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
RETURNING ID INTO :id
"""